name: Software component integration
description: Issue request with all required input informations
title: "[SWC Integration]: "
labels: [pre-integration]
assignees:
- team alas
- team volta
body:
- type: markdown
  attributes:
    value: |
      Fill all required fields related to SWC addition/update
- type: input
  id: swc_name
  attributes:
    label: Software component name
    placeholder: e.g. v1.0
  validations:
    required: true
- type: input
  id: swc_version
  attributes:
    label: Software component version
  validations:
    required: true
- type: dropdown
  id: PIE_version
  attributes:
    label: PIE Version
    description: What version of PIE are you running?
    options:
    - 1.0.0
    - 1.0.1
    - 2.0.0
    - 2.0.1
    - 2.0.2
    - 3.0.0
  validations:
    required: true
- type: input
  id: Artifactory_URL
  attributes:
    label: Artifactory URL to delivery package directory
  validations:
    required: true
