name: Software component integration
description: Issue request with all required input informations
title: "[SWC Integration]: "
labels: [pre-integration]
assignees:
- team alas
- team volta
body:
- type: markdown
  attributes:
    value: |
      Fill all required fields related to SWC addition/update
- type: input
  id: swc_name
  attributes:
    label: Software component name
    description: How can we get in touch with you if we need more info?
  validations:
    required: true
