name: Software component integration
description: Issue request with all required input informations
title: "[SWC Integration]: "
labels: [pre-integration]
assignees:
- team alas
- team volta
body:
- type: markdown
  attributes:
    value: |
      Fill all required fields related to SWC addition/update
- type: input
  id: swc_name
  attributes:
    label: Software component name
  validations:
    required: true
- type: input
  id: swc_version
  attributes:
    label: Software component version
  validations:
    required: true
- type: input
  id: PIE_version
  attributes:
    label: PIE version
  validations:
    required: true
- type: input
  id: AOS_version
  attributes:
    label: AOS version
  validations:
    required: true
- type: input
  id: HW_variant_version
  attributes:
    label: HW variant version
  validations:
    required: true
  attributes:
    label: Artifactory URL to delivery package directory
  validations:
    required: true
  attributes:
